clean: true
objc: true
umbrella_header: NookoSDK/NookoSDK.h
framework_root: NookoSDK
readme: Readme.md

module_version: 0.0.1

author: Mumble
author_url: https://mumbleideas.it/
github_url: https://github.com/Mumble-SRL/NookoSDK-Objc

theme: apple

custom_categories:
  - name: NKManager
    children:
    - NKManager 
    - NKPaginationInfo
  - name: NKParameter
    children: 
    - NKParameter
    - NKSortParameter
    - NKPaginationParameter
    - NKFilterParameter
    - NKGeofenceParameter
    - NKGeneralParameter
  - name: NKProject
    children:
    - NKProject
  - name: NKBlock
    children:
    - NKBlock
  - name: NKSection
    children:
    - NKSection
  - name: NKElement
    children:
    - NKElement
    - NKTextElement
    - NKImagesElement
    - NKImage
    - NKMediaElement
    - NKFile
    - NKCheckboxElement
    - NKWysiwygElement
    - NKDateElement
    - NKAddressElement
    - NKDropdownElement
    - NKPollElement
    - NKGeneralElement
    - NKElementFactory
  - name: NKApiManager
    children:
    - NKApiManager
    - NKResponse
