clean: true
objc: true
umbrella_header: MBurger/MBurger.h
readme: Readme.md
framework_root: MBurger
module_version: 1.0.17
sdk: iphonesimulator

author: Mumble
author_url: https://mumbleideas.it/
github_url: https://github.com/Mumble-SRL/MBurger-iOS

theme: fullwidth

custom_categories:
  - name: MBManager
    children:
    - MBManager 
  - name: MBClient
    children:
    - MBClient
    - MBPaginationInfo
  - name: MBParameter
    children: 
    - MBParameter
    - MBSortParameter
    - MBPaginationParameter
    - MBFilterParameter
    - MBGeofenceParameter
    - MBGeneralParameter
  - name: MBProject
    children:
    - MBProject
    - MBLegalContract
    - MBEvidenceInformations
  - name: MBBlock
    children:
    - MBBlock
  - name: MBSection
    children:
    - MBSection
  - name: MBElement
    children:
    - MBElement
    - MBTextElement
    - MBImagesElement
    - MBImage
    - MBMediaElement
    - MBFile
    - MBCheckboxElement
    - MBWysiwygElement
    - MBDateElement
    - MBAddressElement
    - MBDropdownElement
    - MBDropdownElementOption
    - MBPollElement
    - MBMarkdownElement
    - MBRelationElement
    - MBColorElement
    - MBMultipleElement
    - MBGeneralElement
    - MBElementsFactory
  - name: MBAdmin
    children:
    - MBAdmin
    - MBUploadableElement
    - MBUploadableTextElement
    - MBUploadableImagesElement
    - MBUploadableFilesElement
    - MBUploadableCheckboxElement
    - MBUploadableCholorElement
    - MBUploadableRelationElement
    - MBUploadableElementsFactory
  - name: MBAuth
    children:
    - MBAuth
    - MBUser
    - MBAuthContractAcceptanceParameter
    - MBUserPublishedSection
  - name: MBApiManager
    children:
    - MBApiManager
    - MBMultipartForm
    - MBResponse
  - name: MBPlugin
    children:
    - MBPlugin
  - name: MBUtilities
    children: 
    - MBUtilities

