clean: true
objc: true
umbrella_header: NookoSDK/NookoSDK.h
framework_root: NookoSDK
readme: Readme.md
module_version: 0.0.7
sdk: iphonesimulator

author: Mumble
author_url: https://mumbleideas.it/
github_url: https://github.com/Mumble-SRL/NookoSDK-Objc

theme: jony

custom_categories:
  - name: NKManager
    children:
    - NKManager 
  - name: NKClient
    children:
    - NKClient
    - NKPaginationInfo
  - name: NKParameter
    children: 
    - NKParameter
    - NKSortParameter
    - NKPaginationParameter
    - NKFilterParameter
    - NKGeofenceParameter
    - NKGeneralParameter
  - name: NKProject
    children:
    - NKProject
  - name: NKBlock
    children:
    - NKBlock
  - name: NKSection
    children:
    - NKSection
  - name: NKElement
    children:
    - NKElement
    - NKTextElement
    - NKImagesElement
    - NKImage
    - NKMediaElement
    - NKFile
    - NKCheckboxElement
    - NKWysiwygElement
    - NKDateElement
    - NKAddressElement
    - NKDropdownElement
    - NKDropdownElementOption
    - NKPollElement
    - NKGeneralElement
    - NKElementFactory
  - name: NKAdmin
    children:
    - NKAdmin
    - NKUploadableElement
    - NKUploadableTextElement
    - NKUploadableImagesElement
    - NKUploadableFilesElement
    - NKUploadableElementsFactory
  - name: NKAuth
    children:
    - NKAuth
    - NKUser
  - name: NKApiManager
    children:
    - NKApiManager
    - NKMultipartForm
    - NKResponse
  - name: NKUtilities
    children: 
    - NKUtilities
