clean: true
objc: true
umbrella_header: MBurger/MBurger.h
framework_root: MBurger
readme: Readme.md
module_version: 0.0.7
sdk: iphonesimulator

author: Mumble
author_url: https://mumbleideas.it/
github_url: https://gitlab.mumbleserver.it/iOS/MBurger

theme: jony

custom_categories:
  - name: MBManager
    children:
    - MBManager 
  - name: MBClient
    children:
    - MBClient
    - MBPaginationInfo
  - name: MBParameter
    children: 
    - MBParameter
    - MBSortParameter
    - MBPaginationParameter
    - MBFilterParameter
    - MBGeofenceParameter
    - MBGeneralParameter
  - name: MBProject
    children:
    - MBProject
    - MBLegalContract
  - name: MBBlock
    children:
    - MBBlock
  - name: MBSection
    children:
    - MBSection
  - name: MBElement
    children:
    - MBElement
    - MBTextElement
    - MBImagesElement
    - MBImage
    - MBMediaElement
    - MBFile
    - MBCheckboxElement
    - MBWysiwygElement
    - MBDateElement
    - MBAddressElement
    - MBDropdownElement
    - MBDropdownElementOption
    - MBPollElement
    - MBGeneralElement
    - MBElementsFactory
  - name: MBAdmin
    children:
    - MBAdmin
    - MBUploadableElement
    - MBUploadableTextElement
    - MBUploadableImagesElement
    - MBUploadableFilesElement
    - MBUploadableElementsFactory
  - name: MBAuth
    children:
    - MBAuth
    - MBUser
    - MBAuthContractAcceptanceParameter
  - name: MBPush
    children:
    - MBPush
    - MBPushApiManager
  - name: MBApiManager
    children:
    - MBApiManager
    - MBMultipartForm
    - MBResponse
  - name: MBPlugin
    children:
    - MBPlugin
  - name: MBUtilities
    children: 
    - MBUtilities

